### ISSUE TITLE
Valine comment issue

### ISSUE THREAD

**Issue by baonq243** [DIYgod/diygod.me#138]
I like Valine than disqus.
I enable valine but it not work.
```
  valine:
  enable: true
  appid: l0gKD9w79l8TpDd1sxAAq6z4-MdYXbMMI
  appkey: wcNfMFBNFvMgJJfyeAKWQSmP
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
```
```
av-min.js:15 Uncaught TypeError: Cannot redefine property: applicationId
    at Function.defineProperty (<anonymous>)
    at av-min.js:15
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (av-min.js:15)
    at e (av-min.js:1)
    at Object.<anonymous> (av-min.js:8)
    at e (av-min.js:1)
    at av-min.js:1
    at a (av-min.js:1)
    at Object.<anonymous> (av-min.js:1)
```
